jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      env:
        ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
      name: Buck build
      uses: passy/run-buck@v0.1.0
      with:
        commands: /opt/android-sdk-linux/tools/bin/sdkmanager "build-tools;27.0.3"
          "platforms;android-26" > /dev/null; buck fetch //...; buck build :soloader
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
